name: 'CalVer'
description: 'Generates a CalVer version number'

inputs:
  main:
    description: 'Name of your main branch'
    required: false
    default: 'main'
outputs:
  version:
    description: 'The generated version number'
    value: ${{ steps.calver.outputs.version }}
runs:
  using: "composite"
  steps:
    - id: calver
      run: echo "version=$(./calver/.sh)" >> $GITHUB_OUTPUT
      shell: bash
      env:
        BRANCH: $GITHUB_REF_NAME
        RUN: $GITHUB_RUN_NUMBER
        MAIN: ${{ inputs.main }}