name: 'CalVer'
description: 'Generates a CalVer version number'

inputs:
  main:
    description: 'Name of your main branch'
    required: false
    default: 'main'
outputs:
  version:
    description: 'The generated version number'
    value: ${{ steps.calver.outputs.version }}
runs:
  using: "composite"
  steps:
    - id: calver
      run: |
        OUTPUT=$(curl -sSL https://raw.githubusercontent.com/astorDev/versy/powerful-calver/calver/full.sh | sh)
        echo "$OUTPUT"
        VERSION=$(echo "$OUTPUT" | grep "VERSION is" | awk '{print $3}')
        echo ""
        echo "Extracted version '$VERSION' from previous output"
        echo "version=$VERSION" >> $GITHUB_OUTPUT
      shell: bash
      env:
        BRANCH: ${{ github.ref_name }}
        RUN: ${{ github.run_number }}