name: 'CalVer'
description: 'Generates a CalVer version number'

inputs:
  main:
    description: 'Name of your main branch'
    required: false
    default: 'main'
outputs:
  version:
    description: 'The generated version number'
    value: ${{ steps.calver.outputs.version }}
runs:
  using: "composite"
  steps:
    - id: calver
      run: echo "version=$(curl -sSL https://raw.githubusercontent.com/astorDev/versy/powerful-calver/calver/full.sh | sh)" >> $GITHUB_OUTPUT
      shell: bash
      env:
        RUN: ${{ github.run_number }}