name: 'CalVer'
description: 'Generates a CalVer version number'

inputs:
  main:
    description: 'Name of your main branch'
    required: false
    default: 'main'
  script-branch:
    description: 'Name of the calver script version'
    required: false
    default: 'main'
outputs:
  version:
    description: 'The generated version number'
    value: ${{ steps.calver.outputs.version }}
runs:
  using: "composite"
  steps:
    - id: calver
      run: |
        VERSION=$(curl -sSL https://raw.githubusercontent.com/astorDev/versy/${SCRIPT_BRANCH}/.sh | sh -s calver)
        echo "version=$VERSION" >> $GITHUB_OUTPUT
      shell: bash
      env:
        SCRIPT_BRANCH: ${{ inputs.script-branch }}
        BRANCH: ${{ github.ref_name }}
        RUN: ${{ github.run_number }}