name: 'CalVer'
description: 'Generates a CalVer version number'

inputs:
  main:
    description: 'Name of your main branch'
    required: false
    default: 'main'
outputs:
  version:
    description: 'The generated version number'
    value: ${{ steps.calver.outputs.version }}
runs:
  using: "composite"
  steps:
    # - uses: actions/checkout@v4
    #   with:
    #     repository: 'astorDev/versy'
    #     path: 'versy-calver'
    # - id: suffix
    #   run: echo "suffix=$(./versy-calver/suffix.sh)" >> $GITHUB_OUTPUT
    #   shell: bash
    #   env:
    #     BRANCH: ${{ github.ref_name }}
    #     MAIN: ${{ inputs.main }}
    - id: calver
      run: |
        OUTPUT=$(curl -sSL https://raw.githubusercontent.com/astorDev/versy/powerful-calver/calver/full.sh | sh)
        echo "$OUTPUT"
        VERSION=$("$OUTPUT" | grep "VERSION is" | awk '{print $3}')
        echo "version=$OUTPUT" >> $GITHUB_ENV
      shell: bash
      env:
        BRANCH: ${{ github.ref_name }}
        RUN: ${{ github.run_number }}