name: 'Nuget Pack & Publish'
description: 'Packs & Publishes Nuget Package'

inputs:
  version:
    description: 'Project Version to publish'
    required: true
  project:
    description: 'Path to .csproj file (without .csproj and `./`)'
    required: true
  nuget-api-key:
    description: 'Nuget API key'
    required: true
  nuget-source:
    description: 'Nuget source'
    required: false
    default: 'https://api.nuget.org/v3/index.json'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - uses: actions/checkout@v4
      with:
        repository: 'astorDev/versy'
        path: 'versy-nuget'
    - uses: actions/setup-dotnet@v4
    - shell: bash
      env:
        VERSION: ${{ inputs.version }}
        PROJECT: ${{ inputs.project }}
        NUGET_API_KEY: ${{ inputs.nuget-api-key }}
        NUGET_SOURCE: ${{ inputs.nuget-source }}
      run: sh ./versy-nuget/nuget/.sh