name: 'CalVer Nuget'
description: 'Packs & Publishes Nuget with generated CalVer version number'

inputs:
  main:
    description: 'Name of your main branch'
    required: false
    default: 'main'
  project:
    description: 'Path to .csproj file (without .csproj and `./`)'
    required: true
  nuget_api_key:
    description: 'Nuget API key'
    required: true
  nuget_source:
    description: 'Nuget source'
    required: false
    default: 'https://api.nuget.org/v3/index.json'
runs:
  using: "composite"
  steps:
    - id: version
      uses: astorDev/versy/calver@deconflicting
      with:
        main: ${{ inputs.main }}
    - uses: astorDev/versy/nuget@deconflicting
      with:
        version: ${{ steps.version.outputs.version }}
        project: ${{ inputs.project }}
        nuget_api_key: ${{ inputs.nuget_api_key }}
        nuget_source: ${{ inputs.nuget_source }}