name: 'CalVer Nuget'
description: 'Packs & Publishes Nuget with generated CalVer version number'

inputs:
  main:
    description: 'Name of your main branch'
    required: false
    default: 'main'
  script-branch:
    description: 'Underlying script branch'
    required: false
    default: 'main'
  project:
    description: 'Path to .csproj file (without .csproj and `./`)'
    required: true
  nuget_api_key:
    description: 'Nuget API key'
    required: true
  nuget_source:
    description: 'Nuget source'
    required: false
    default: 'https://api.nuget.org/v3/index.json'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4 # for the csproj
    - run: curl -sSL $SOURCING_URL/.sh | sh -s calver_nuget
      shell: bash
      env:
        SOURCING_URL: https://raw.githubusercontent.com/astorDev/versy/${{ inputs.script-branch }}
        BRANCH: ${{ github.ref_name }}
        RUN: ${{ github.run_number }}
        MAIN: ${{ inputs.main }}
        PROJECT: ${{ inputs.project }}
        NUGET_API_KEY: ${{ inputs.nuget_api_key }}
        NUGET_SOURCE: ${{ inputs.nuget_source }}