on:
  push:
      
jobs:
  publish_calver_nuget:
    runs-on: ubuntu-latest
    steps:
      - uses: astorDev/versy/nuget@main
        with:
          project: 'nuget/Versy.Nuget'
          nuget_api_key: ${{ secrets.NUGET_API_KEY }}