on:
  push:
    paths:
      - '.github/workflows/calver-docker.yaml'
      - 'push_docker/**'
      - 'calver/docker/**'
      - '.sh'
  workflow_dispatch:
    
jobs:
  local-action:
    runs-on: ubuntu-latest
    steps:
      - uses: astorDev/versy/calver/docker@docker-platform
        with:
          script-branch: ${{ github.ref_name }}
          image: 'vosarat/versy-hello'
          build-context-path: '.'
          dockerfile-path: 'push_docker/Dockerfile'
          docker-login: vosarat
          docker-password: ${{ secrets.DOCKER_PASSWORD }}