on:
  push:
    paths:
      - '.github/workflows/calver.yaml'
      - 'calver/**'
      - '.sh'
      
jobs:
  local-action:
    runs-on: ubuntu-latest
    steps:
      - id: version
        uses: astorDev/versy/calver@main
        with:
          script-branch: ${{ github.ref_name }}
      - run: |
          if [ "${{ steps.version.outputs.version }}" = "" ]; then
            echo "No version found"
            exit 1
          fi

          echo "Received version is ${{ steps.version.outputs.version }}"