on:
  push:
    paths:
      - '.github/workflows/calver-nuget.yaml'
      - 'calver/nuget/**'
      - '.sh'
jobs:
  local-action:
    runs-on: ubuntu-latest
    steps:
      - uses: astorDev/versy/calver/nuget@nuget-naming-fix
        with:
          project: 'nuget/Versy'
          nuget-api-key: ${{ secrets.NUGET_API_KEY }}