on:
  push:
    paths:
      - '.github/workflows/calver-nuget.yaml'
      - 'calver/nuget/**'
      - 'nuget/**'
      - 'dotnet/lib/**'
      - '.sh'
jobs:
  local-action:
    runs-on: ubuntu-latest
    steps:
      - uses: astorDev/versy/calver/nuget@main
        with:
          project: 'dotnet/lib/Versy'
          script-branch: ${{ github.ref_name }}
          nuget-api-key: ${{ secrets.NUGET_API_KEY }}