on:
  push:
    paths:
      - '.github/workflows/calver-docker.yaml'
      - 'docker/**'
      - 'calver/docker/**'
      - '.sh'
  workflow_dispatch:
    
jobs:
  local-action:
    runs-on: ubuntu-latest
    steps:
      - uses: astorDev/versy/calver/docker@main
        with:
          script-branch: ${{ github.ref_name }}
          image: 'vosarat/versy-hello'
          build-context-path: 'docker'
          dockerfile-path: 'docker/Dockerfile'
          docker-login: vosarat
          docker-password: ${{ secrets.DOCKER_PASSWORD }}
          use-buildx: false