on:
  push:
    paths:
      - '.github/workflows/flutter.yaml'
      - 'flutter/beta/Dockerfile'
  workflow_dispatch:
    
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: astorDev/versy/calver/docker@main
        with:
          script-branch: ${{ github.ref_name }}
          image: 'vosarat/flutter-beta'
          build-context-path: 'flutter/beta'
          dockerfile-path: 'flutter/beta/Dockerfile'
          docker-login: vosarat
          docker-password: ${{ secrets.DOCKER_PASSWORD }}