on:
  push:
      
jobs:
  ouput_version:
    runs-on: ubuntu-latest
    steps:
      - id: version
        uses: astorDev/versy/calver@main
      - run: echo "Received version is ${{ steps.version.outputs.version }}"
  publish_calver_nuget:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v2
      - uses: astorDev/versy/calver@main
      - uses: astorDev/versy/nuget@nuget-action
        with:
          version: ${{ steps.version.outputs.version }}
          project: 'nuget/Versy.Nuget'
          nuget_api_key: ${{ secrets.NUGET_API_KEY }}