on:
  push:
      
jobs:
  ouput_version:
    runs-on: ubuntu-latest
    steps:
      - id: version
        uses: astorDev/versy/calver@main
      - run: echo "Received version is ${{ steps.version.outputs.version }}"
  publish_nuget:
    runs-on: ubuntu-latest
    steps:
      - uses: astorDev/versy/calver/nuget@nuget-action
        with:
          project: './calver/nuget/CalVer.Nuget'