on:
  push:
      
jobs:
  ouput_version:
    runs-on: ubuntu-latest
    steps:
      - id: version
        uses: astorDev/versy/calver@deconflicting
      - run: |
          if [ "${{ steps.version.outputs.version }}" = "" ]; then
            echo "No version found"
            exit 1
          fi

          echo "Received version is ${{ steps.version.outputs.version }}"
  publish_calver_nuget:
    runs-on: ubuntu-latest
    steps:
      - uses: astorDev/versy/calver/nuget@deconflicting
        with:
          project: 'nuget/Versy.Nuget'
          nuget_api_key: ${{ secrets.NUGET_API_KEY }}