on:
  push:
      
jobs:
  publish_nuget:
    runs-on: ubuntu-latest
    steps:
      - uses: astorDev/versy/calver/nuget@main
        with:
          project: 'nuget/Versy.Nuget'
          nuget_api_key: ${{ secrets.NUGET_API_KEY }}
          version: 1.1.${{ github.run_number }}-${{ github.ref_name }}