on:
  push:
    paths:
      - '.github/workflows/nuget.yaml'
      - 'nuget/**'
      - '.sh'
      
jobs:
  publish_nuget:
    runs-on: ubuntu-latest
    steps:
      - uses: astorDev/versy/nuget@main
        with:
          project: 'nuget/Versy'
          nuget-api-key: ${{ secrets.NUGET_API_KEY }}
          version: 1.1.${{ github.run_number }}-${{ github.ref_name }}