on:
  push:
      
jobs:
  suffix:
    runs-on: ubuntu-latest
    steps:
      - run: curl -sSL $SOURCING_URL/.sh | sh -s suffix
        env:
          SOURCING_URL: https://raw.githubusercontent.com/astorDev/versy/${{ github.ref_name }}
          BRANCH: ${{ github.ref_name }}
  calver:
    runs-on: ubuntu-latest
    steps:
      - run: curl -sSL $SOURCING_URL/.sh | sh -s calver
        env:
          SOURCING_URL: https://raw.githubusercontent.com/astorDev/versy/${{ github.ref_name }}
          BRANCH: ${{ github.ref_name }}
          RUN: ${{ github.run_number }}
  nuget:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: curl -sSL $SOURCING_URL/.sh | sh -s nuget
        env:
          SOURCING_URL: https://raw.githubusercontent.com/astorDev/versy/${{ github.ref_name }}
          VERSION: 2.3.${{ github.run_number }}
          PROJECT: 'nuget/Versy.Nuget'
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}