on:
  push:
    paths:
      - '.github/workflows/suffix.yaml'
      - 'suffix/**'
jobs:
  remote_call:
    runs-on: ubuntu-latest
    steps:
      - run: curl -sSL https://raw.githubusercontent.com/astorDev/versy/$BRANCH/suffix/marketplacing/.sh | sh
        env:
          BRANCH: ${{ github.ref_name }}