on:
  push:
    paths:
      - '.github/workflows/suffix-marketplacing.yaml'
      - 'suffix/marketplacing/**'
jobs:
  remote-call:
    runs-on: ubuntu-latest
    steps:
      - run: curl -sSL https://raw.githubusercontent.com/astorDev/versy/$BRANCH/suffix/marketplacing/.sh | sh
        env:
          BRANCH: ${{ github.ref_name }}
  local-action:
    runs-on: ubuntu-latest
    steps:
      - id: suffix 
        uses: astorDev/versy/suffix/marketplacing@suffix-marketplaced
        with:
          script-branch: ${{ github.ref_name }}
      - run: echo "Suffix is '${{ steps.suffix.outputs.suffix }}'"
  marketplaced-action:
    runs-on: ubuntu-latest
    steps:
      - id: suffix
        uses: astorDev/suffix/@main
      - run: echo "Suffix is '${{ steps.suffix.outputs.suffix }}'"